networks:
  container_network:
    name: container_network

services:
  checkout_green:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./.env:/.env
     - ./data:/data
    networks:
      - container_network