networks:
  container_network:
    name: container_network

services:
  checkout_green:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./data:/Checkout_Server/data:rw
     - ./src/templates:/Checkout_Server/src/templates:rw
    networks:
      - container_network